### ISSUE TITLE
collapsible group: all headings are currently h3

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#82]
example page:
https://elections.usdr.dev/faq/

top-level headings should be h2
inner-level headings should be h3

**Comment by legarlin** [comment]
it's possible to adjust this?

**Comment by legarlin** [comment]
if the issue is more so the experience of selecting the group such that you can adjust it, i'll probably need some help with the design / UX of that since gutenberg doesn't make it super easy to select higher level groups

**Comment by paulschreiber** [comment]
This is unrelated to selection.

**Comment by legarlin** [comment]
the figma mocks have the top-level headings at an h3 (24px) -- which is also what's mapped out in code.

and the figma mocks also have the inner subsections at an h5 (18px) -- also mapped out in code.

i think the issue here is that you need to select the inner collapsible group from the group selector and change the heading options in the inspector panel. when i do that, the inner selections look correct.

**Comment by legarlin** [comment]
it's implemented that way because there are 3 types of headers. the results page has the 3rd -- the h2 example. and with this, the rendering can be done with the proper tags (h2/h3/h5). otherwise, i'm not sure how else to specify those styles other than overriding. CSS rules

the UX likely could be adjusted, either with better helper text. would be good to ask Constance about that

**Comment by paulschreiber** [comment]
The font size can be adjusted, but semantically/accessibility-wise, we need to use h2 and h3.

**Comment by legarlin** [comment]
i'm not entirely sure i'm following what needs to be adjusted at this point since h2 means something else? this is just based on the mocks. but feel free to adjust as you see fit!
